name: GitHub City

on:
  workflow_dispatch:  # Executar manualmente

jobs:
  github-city:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Garante que o repositório esteja acessível

      - name: Generate GitHub City visualization
        uses: lowlighter/metrics@latest
        with:
          filename: output/metrics.plugin.skyline.city.svg  # Define a pasta de saída "output"
          token: NOT_NEEDED  # Sem necessidade de token
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2024  # Ano que você quer exibir
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }

      - name: Commit and push the GitHub City visualization to the repository
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = './output/metrics.plugin.skyline.city.svg';
            
            const content = fs.readFileSync(path, 'utf8');
            const { execSync } = require('child_process');
            
            execSync('git config --global user.name "github-actions[bot]"');
            execSync('git config --global user.email "github-actions[bot]@users.noreply.github.com"');
            execSync('git add .');
            execSync('git commit -m "Add GitHub City visualization"');
            execSync('git push');
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necessário para realizar o push

